# FUNCTIONSSSSSSSS

## Dataset

In [13]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [14]:
d = pd.read_csv("clean_books.csv")
d

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,1
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,0
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,1
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,0
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,1
...,...,...,...,...,...,...,...
346,Winter of the World: Book Two of the Century T...,Ken Follett,4.5,10760,15,2012,0
347,Women Food and God: An Unexpected Path to Almo...,Geneen Roth,4.2,1302,11,2010,1
348,Wonder,R. J. Palacio,4.8,21625,9,2013,0
349,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,0
350,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,1

In [15]:
# lay out for v2 idea
# # main -
#       | - option
#          |- option in option

## Book by name

In [16]:
def searchname():
    val = input("Book Name: ")
    typ= "Name"
    out = d[typ].str.contains(val, case=False, na=False) # used AI help for this line
    out = d[out]

    if len(out) ==0 :
        return "Book not found"
    
    elif len(out) ==1 :
        return out
   
    else:
        y = input(f"{out[['Name', 'Author']]} \n please choose a book by index")
        return out.iloc[int(y)]

In [17]:
searchname()

,Name,Author,User Rating,Reviews,Price,Year,Genre
252,The Great Gatsby,F. Scott Fitzgerald,4.4,11616,7,2012,0

## Book by specifics

In [18]:
def search(val, typ):
    out = d[typ].str.contains(val, case=False, na=False) # used AI help for this line
    out = d[out]

    if len(out) ==0 :
        return "Book not found"
    
    elif len(out) ==1 :
        return out
   
    else:
        y = input(f"{out[['Name', 'Author']]} \n please choose a book by index")
        return out.iloc[int(y)]

In [19]:
def specific(d):
    specific = input("Insert number followed by space then the specific available. \n 1. Name \n 2. Author \n 3. User Rating \n 4. Price \n 5. Genre \n ONLY ONE SPECIFIC ")
    
    num, val = specific.split(" ", 1)
    num = int(num)

    match num:
        case 1:
            return search(val, "Name")
        case 2:
            return search(val, "Author")
        case 3:
            return search(val, "User Rating")
        case 4:
            return search(val, "Price")
        case 5:
            return search(val, "Genre")
        case _:
            return "Invalid option"

## Book recommend

In [20]:
def searchtype(typ):
    if typ == 'Price':
        out = d.sort_values(by = typ, ascending=True)
    else:
        out = d.sort_values(by = typ, ascending=False)

    return out

In [21]:
def recommend():
    r = int(input("Recommend by: \n 1. Rating \n 2. Price \n 3. Reviews \n 4. Year \n 5. Genre"))
    match r:
        case 1:
            return searchtype("User Rating")
        case 2:
            return searchtype("Price")
        case 3:
            return searchtype("Reviews")
        case 4:
            return searchtype("Year")
        case 5:
            return searchtype("Genre")
        case _:
            return "Invalid option"

# Main

In [22]:
def main():
    x = int(input("Choose service : \n 1. Book by name \n 2. Book search by specifics \n 3. Book recommendation"))
    match x:
        case 1:
            searchname()
        case 2:
            specific(d)
        case 3:
            recommend()

In [23]:
main() # get project running

ValueError: invalid literal for int() with base 10: ''