In [209]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [193]:
d = pd.read_csv("books.csv")
d

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [194]:
#x = input("Choose service : \n 1. Book by name \n 2. Book search by specifics \n 3. Book recommendation")

In [ ]:
# lay out for v2 idea
# # main -
#       | - option
#          |- option in option

## Book by name

In [ ]:
def search(val, typ):
    out = d[typ].str.contains(val, case=False, na=False) # used AI help for this line
    out = d[out]

    if len(out) ==0 :
        return "Book not found"
    
    elif len(out) ==1 :
        return out
   
    else:
        y = input(f"{out[['Name', 'Author']]} \n please choose a book by index")
        return out.iloc[int(y)]

In [196]:
search("The great gatsby" , "Name")

Name              The Great Gatsby
Author         F. Scott Fitzgerald
User Rating                    4.4
Reviews                      11616
Price                            7
Year                          2013
Genre                      Fiction
Name: 395, dtype: object

## Book by specifics

In [199]:
def specific(d):
    specific = input("Insert number followed by space then the specific available. \n 1. Name \n 2. Author \n 3. User Rating \n 4. Price \n 5. Genre \n ONLY ONE SPECIFIC ")
    
    num, val = specific.split(" ", 1)
    num = int(num)

    match num:
        case 1:
            return search(val, "Name")
        case 2:
            return search(val, "Author")
        case 3:
            return search(val, "User Rating")
        case 4:
            return search(val, "Price")
        case 5:
            return search(val, "Genre")
        case _:
            return "Invalid option"

In [204]:
specific(d)

,Name,Author,User Rating,Reviews,Price,Year,Genre
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction

## Book recommend

In [240]:
def searchtype(typ):
    if typ == 'Price':
        out = d.sort_values(by = typ, ascending=True)
    else:
        out = d.sort_values(by = typ, ascending=False)

    return out

In [ ]:
def recommend():
    r = int(input("Recommend by: \n 1. Rating \n 2. Price \n 3. Reviews \n 4. Year \n 5. Genre"))
    match r:
        case 1:
            return searchtype("User Rating")
        case 2:
            return searchtype("Price")
        case 3:
            return searchtype("Reviews")
        case 4:
            return searchtype("Year")
        case 5:
            return searchtype("Genre")
        case _:
            return "Invalid option"

In [241]:
searchtype("Price")

,Name,Author,User Rating,Reviews,Price,Year,Genre
42,"Cabin Fever (Diary of a Wimpy Kid, Book 6)",Jeff Kinney,4.8,4505,0,2011,Fiction
461,The Short Second Life of Bree Tanner: An Eclip...,Stephenie Meyer,4.6,2122,0,2010,Fiction
71,"Diary of a Wimpy Kid: Hard Luck, Book 8",Jeff Kinney,4.8,6812,0,2013,Fiction
381,The Getaway,Jeff Kinney,4.8,5836,0,2017,Fiction
116,Frozen (Little Golden Book),RH Disney,4.7,3642,0,2014,Fiction
...,...,...,...,...,...,...,...
346,The Book of Basketball: The NBA According to T...,Bill Simmons,4.7,858,53,2009,Non Fiction
151,Hamilton: The Revolution,Lin-Manuel Miranda,4.9,5867,54,2016,Non Fiction
473,The Twilight Saga Collection,Stephenie Meyer,4.7,3801,82,2009,Fiction
70,Diagnostic and Statistical Manual of Mental Di...,American Psychiatric Association,4.5,6679,105,2014,Non Fiction
69,Diagnostic and Statistical Manual of Mental Di...,American Psychiatric Association,4.5,6679,105,2013,Non Fiction